### ISSUE TITLE
Update external_vars domain port

### ISSUE THREAD

**Issue by jpconfessor** [bluecatlabs/bluecat-gateway-ansible-module#5]
Currently, we have port localhost:5000 which is only used for development purposes, but not in production (by default). I would suggest removing the port from that variable in order to use the default one (80)

Current:
`domain: localhost:5000`

Desired:
`domain: localhost`

Having port 5000 will cause the following error:
`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /logout (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc07ee228d0>: Failed to establish a new connection: [Errno 111] Connection refused',))`

**Comment by sharma-anshul** [comment]
Hey, thanks for bringing it to our notice! I have a pull request open currently to address this: https://github.com/bluecatlabs/bluecat-gateway-ansible-module/pull/4

As soon as this is merged in, this issue should be fixed.

**Comment by xiax** [comment]
Resolved by #4
